spring:
  batch:
    jdbc:
      initialize-schema: never
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=utf8
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
